### ISSUE TITLE
No old files found

### ISSUE THREAD

**Issue by starlet-lxxx** [itodnerd/WATT-simulate#1]
Hello! An error occurred when I ran the script. What is tracefile and outdir? What tracefile satisfies the conditions? Has tracefile been processed? Can you provide some source files that have been processed?

Specific details are as follows:

root@ubuntu:/WATT-simulate/build# ./evalAccessTable tracefile outdir
No old files found
lru
Segmentation fault (core dumped)

thank you.

**Comment by itodnerd** [comment]
Just for other persons looking at this issue:

as *outdir* you should name the directory where the results should be stored. (e.g. `./out`)

Tracefiles can be found [here](https://github.com/itodnerd/WATT-traces/tree/main/WATT_competition_traces)

I am working right now on adding more formats of tracefiles. [(somehow similar to caffein)](https://github.com/ben-manes/caffeine)
